######################## default configuration ####################
baseURL = "http://ucenlist.org/"
title = "UCENLIST - ​Trung tâm UNESCO Bồi dưỡng Kỹ năng sống và ứng dụng thiền Vipassana"
theme = "hugo"
defaultContentLanguage = "vi"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "UA-20208042-25" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true