############################# Vietnamese ############################
[vi]
languageName = "Vi"
title = "Trung tâm UNESCO Bồi dưỡng Kỹ năng sống và ứng dụng thiền Vipassana"
contentDir = "content/vietnamese" # content/vietnamese
weight = 1
########### footer content ##########
footer_menu_left = "Thiền Vipassana"
footer_menu_middle = "Khoá thiền"
footer_menu_right = "Trung tâm UCENLIST"
footer_content = "Trung tâm UNESCO Bồi dưỡng Kỹ năng sống và ứng dụng thiền Vipassana."
# copyright
copyright = "UCENLIST - ​Trung tâm UNESCO Bồi dưỡng Kỹ năng sống và ứng dụng thiền Vipassana<br>​Tổ chức hoạt động phi lợi nhuận trực thuộc Liên hiệp các hội UNESCO Việt Nam"