# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
identifier = "vipassana"
name = "Thiền Vipassana"
url = "#"
weight = 2


[[main]]
name = "Thiền Vipasana là gì?"
url = "vipassana"
parent = "vipassana"
weight = 1

[[main]]
name = "Nghệ thuật sống thiền Vipassana?"
url = "nghe-thuat-song"
parent = "vipassana"
weight = 2

[[main]]
name = "Phương pháp & Nội quy"
url = "phuong-phap"
parent = "vipassana"
weight = 3

[[main]]
name = "Hỏi đáp"
url = "hoi-dap"
parent = "vipassana"
weight = 4

[[main]]
name = "Blog"
url = "blog"
weight = 3

[[main]]
name = "About"
url = "about"
weight = 4


[[main]]
name = "Contact"
url = "contact"
weight = 5

# footer menu left
[[footer_left]]
name = "About Us"
url = "#"

[[footer_left]]
name = "Quick Start"
url = "#"

[[footer_left]]
name = "Pricing"
url = "pricing"


# footer menu middle
[[footer_middle]]
name = "Pricing"
url = "pricing"

[[footer_middle]]
name = "Platform"
url = "#"

[[footer_middle]]
name = "Features"
url = "#"

# footer menu right
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy"

[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions"

[[footer_right]]
name = "FAQ"
url = "faq"