# main menu
[[main]]
name = "Trang chủ"
url = "/"
weight = 1

[[main]]
identifier = "about"
name = "Thiền Vipassana"
url = "#"
weight = 2


[[main]]
name = "Thiền Vipasana là gì?"
url = "vipassana"
parent = "about"
weight = 1

[[main]]
name = "Thiền sư S.N Goenka"
url = "sngoenka"
parent = "about"
weight = 2

[[main]]
name = "Nghệ thuật sống: thiền Vipassana"
url = "nghe-thuat-song"
parent = "about"
weight = 3

[[main]]
name = "Phương pháp & Nội quy"
url = "phuong-phap"
parent = "about"
weight = 4

[[main]]
name = "Hỏi đáp"
url = "faq"
parent = "about"
weight = 5

[[main]]
identifier = "courses"
name = "Các khoá thiền"
url = "#"
weight = 3

[[main]]
name = "Khoá thiền tại Hà Nội"
url = "ucenlist-vma-hn"
parent = "courses"
weight = 1

[[main]]
name = "Khoá thiền tại TP Hồ Chí Minh"
url = "ucenlist-vma-hcmc"
parent = "courses"
weight = 2

[[main]]
name = "Tin tức"
url = "tin-tuc"
weight = 4

[[main]]
name = "UCENLIST"
url = "ucenlist"
weight = 5


[[main]]
name = "Liên hệ"
url = "contact"
weight = 6

# footer menu left
[[footer_left]]
name = "Thiền Vipassana là gì?"
url = "/vipassana"
weight = 1

# footer menu left
[[footer_left]]
name = "Thiền sư S.N Goenka"
url = "/sngoenka/"
weight = 2

[[footer_left]]
name = "Nghệ thuật sống"
url = "/nghe-thuat-song"
weight = 3

[[footer_left]]
name = "Phương pháp & Nội quy"
url = "/phuong-phap"
weight = 4

[[footer_left]]
name = "Hỏi đáp"
url = "faq"
weight = 5

# footer menu middle
[[footer_middle]]
name = "Khoá thiền tại Hà Nội"
url = "ucenlist-vma-hn"
weight = 1

[[footer_middle]]
name = "Khoá thiền tại TP Hồ Chí Minh"
url = "ucenlist-vma-hcmc"
weight = 2

# footer menu right
[[footer_right]]
name = "Giới thiệu"
url = "ucenlist"

[[footer_right]]
name = "Liên hệ"
url = "contact"