# main menu
[[main]]
name = "Trang chủ"
url = "/"
weight = 1

[[main]]
identifier = "about"
name = "Thiền Vipassana"
url = "#"
weight = 2


[[main]]
name = "Thiền Vipasana là gì?"
url = "vipassana"
parent = "about"
weight = 1

[[main]]
name = "Thiền sư S.N Goenka"
url = "sngoenka"
parent = "about"
weight = 2

[[main]]
name = "Nghệ thuật sống thiền Vipassana?"
url = "nghe-thuat-song"
parent = "about"
weight = 3

[[main]]
name = "Phương pháp & Nội quy"
url = "phuong-phap"
parent = "about"
weight = 4

[[main]]
name = "Hỏi đáp"
url = "faq"
parent = "about"
weight = 5

[[main]]
name = "Tin tức"
url = "news"
weight = 3

[[main]]
name = "UCENLIST"
url = "ucenlist"
weight = 4


[[main]]
name = "Liên hệ"
url = "contact"
weight = 5

# footer menu left
[[footer_left]]
name = "Thiền Vipassana là gì?"
url = "/vipassana"
weight = 1

# footer menu left
[[footer_left]]
name = "Thiền sư S.N Goenka"
url = "/sngoenka/"
weight = 2

[[footer_left]]
name = "Nghệ thuật sống"
url = "/nghe-thuat-song"
weight = 3

[[footer_left]]
name = "Phương pháp & Nội quy"
url = "/phuong-phap"
weight = 4

# footer menu middle
[[footer_middle]]
name = "Pricing"
url = "pricing"

[[footer_middle]]
name = "Platform"
url = "#"

[[footer_middle]]
name = "Features"
url = "#"

# footer menu right
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy"

[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions"

[[footer_right]]
name = "FAQ"
url = "faq"