---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Homepage
- type: document
  path: exampleSite/content/vietnamese/_index.md
  label: Homepage (vi)
- type: heading
  label: Blog
- type: document
  path: exampleSite/content/vietnamese/tin-tuc/_index.md
  label: Blog Page (vi)
- type: directory
  path: exampleSite/content/vietnamese/tin-tuc
  label: Blog Post (vi)
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - post
- type: heading
  label: Others Page
- type: document
  path: exampleSite/content/vietnamese/contact/_index.md
  label: Contact (vi)
- type: document
  path: exampleSite/content/vietnamese/pricing/_index.md
  label: Pricing (vi)
- type: document
  path: exampleSite/content/vietnamese/faq/_index.md
  label: FAQ (vi)
- type: heading
  label: All Pages
- type: directory
  path: exampleSite/content
  label: All Pages
  create: all
  match: "**/*"
  exclude: _index.md
  templates:
  - new-page
- type: heading
  label: Configuration
- type: document
  path: exampleSite/config/_default/config.toml
  label: Configuration
- type: document
  path: exampleSite/config/_default/params.toml
  label: Parameters
- type: document
  path: config.toml
  label: Variables & Plugins
  match: "**/*"
- type: document
  path: exampleSite/config/_default/languages.toml
  label: Languages
- type: document
  path: exampleSite/config/_default/menus.vi.toml
  label: Menu (vi)
  match: "**/*"
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
